#!/bin/bash
#SBATCH -J bsr_breit
#SBATCH -o bsr_breit.out
#SBATCH -e bsr_breit.err
#SBATCH -N 4
#SBATCH --ntasks-per-node 64
#SBATCH -n 256
#SBATCH -p development
#SBATCH -t 02:00:00
#SBATCH -A TG-PHY090031

  set echo

  ibrun ~/BIN/bsr_breit3_mpi klsp1=1 klsp2=12  


