#!/bin/bash
#SBATCH -J bsr_hdb
#SBATCH -o bsr_hdb.out
#SBATCH -e bsr_hdb.err
#SBATCH --ntasks-per-node 64
#SBATCH -n 256
#SBATCH -N 4
#SBATCH -p development
#SBATCH -t 02:00:00
#SBATCH -A TG-PHY090031

  set echo

for n in 001 002 003 004 005 006 007 008 009 010 011 012
do
  ibrun ~/BIN/bsr_hdb3 klsp=$n  p=16 q=16 
done

